name: GitHub Pages Deploy

on:
  push:
    branches:
      - main  # 触发自动部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 如果使用子模块需要这个参数

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'  # 指定 Hugo 版本
          extended: true           # 如果需要 extended 版本

      - name: Build
        run: hugo --minify --gc     # 构建命令，添加优化参数

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          external_repository: weenable/weenable.github.io  # 部署到的仓库
          publish_dir: ./public    # Hugo 生成的静态文件目录
          keep_files: false        # 是否保留历史文件
          commit_message: ${{ github.event.head_commit.message }}  # 使用原始提交信息
